### ISSUE TITLE
CppCheck addons are not installed

### ISSUE THREAD

**Issue by GregAujay** [Thieum/ChocolateyPackages#10]
In CppCheck Windows MSI installers the python addons are not installed by default so chocolatey does not install them.

Can you add an option to install them or install them by default?

Tested with CppCheck-1.87-x64-Setup.msi

**Comment by Thieum** [comment]
@GregAujay asked what could be the option to trigger this install in cppcheck forums, as I couldn't find anything in the docs, or the msi help that could help me achieve that:
https://sourceforge.net/p/cppcheck/discussion/general/thread/5cdeea4096/

Once I get an answer, I'll try to add the option.

**Comment by Thieum** [comment]
Considering the features defined here: https://github.com/danmar/cppcheck/blob/master/win_installer/cppcheck.wxs
Considering this hint about installing features from the command line with wix: https://stackoverflow.com/questions/246329/wix-how-to-select-features-from-command-line
I managed to achieve a full install with the following command-line:

msiexec /i cppcheck-1.87-x64-Setup.msi ADDLOCAL=CppcheckCore,CLI,GUI,Translations,ConfigFiles,PlatformFiles,PythonAddons,CRT

Complete doesn't seem to work, but putting all the features works fine. It makes it more fragile to changes if cppcheck devs add/remove features, but I don't think it happens so often.

The complete version of the package will be available soon there : https://chocolatey.org/packages/cppcheck

**Comment by GregAujay** [comment]
👍
