### ISSUE TITLE
cppcheck 2.11 is incorrect

### ISSUE THREAD

**Issue by aminya** [Thieum/ChocolateyPackages#22]
cppcheck 2.11 is not pushed to GitHub although it is published on Chocolatey
https://community.chocolatey.org/packages/cppcheck

The source uses 2.10:
https://github.com/Thieum/ChocolateyPackages/blob/cb24c81d6903be580e6984e07d189b1e68c6e4d9/cppcheck/tools/chocolateyInstall.ps1#L4

**Comment by Thieum** [comment]
pushed in https://github.com/Thieum/ChocolateyPackages/commit/c7652425bcb18cd1fdb4121d351439bd5cb30f60
