### ISSUE TITLE
Cppcheck 2.15.0 is available

### ISSUE THREAD

**Issue by anoymouserver** [Thieum/ChocolateyPackages#23]
Since yesterday the Cppcheck version 2.15.0 is available ([news article](https://sourceforge.net/p/cppcheck/news/2024/08/cppcheck-2150/), [GitHub release](https://github.com/danmar/cppcheck/releases/tag/2.15.0)).

Unfortunately this repo and the released package are a few versions behind, but I hope it will still be maintained.

**Comment by ncook-hxgn** [comment]
Yup, 2.16 dropped now with SARIF output support.

**Comment by Thieum** [comment]
2.16.0 should appear here: https://community.chocolatey.org/packages/cppcheck/2.16.0
