### ISSUE TITLE
staruml 3 is available

### ISSUE THREAD

**Issue by tomtomsen** [Thieum/ChocolateyPackages#6]
hi!

Staruml 3 is available. 
are you planning to be the owner of that choco repo too?
are you going to create a new choco package, like staruml3?

i would like to make a pull request for that. if you dont mind.

**Comment by Thieum** [comment]
Feel free to create your own choco package or send a pull request. I'll try to publish it if you send a pull request.

**Comment by Thieum** [comment]
Package is submitted, and will be located here : https://chocolatey.org/packages/staruml3

There's a a newer version, 3.0.1 that is available - will check later to update, once the first version is accepted.
